### ISSUE TITLE
Page titles too small

### ISSUE THREAD

**Issue by budupaul** [surveyjs/survey-library#1479]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?
Page titles seem very small in comparison to my panel titles. How and where exactly should I modify the css fie of the survey in order to make the font of the page titles larger? Thank you

**Comment by tsv2013** [comment]
```CSS
.sv_main .sv_container .sv_body .sv_p_root .sv_page_title {
  font-size: 40px;
}
```
Here is the sample - https://next.plnkr.co/edit/2EHtjoH5g7zvAU6B
