### ISSUE TITLE
Overriding css classes in React

### ISSUE THREAD

**Issue by kelvin-homann** [surveyjs/survey-library#1864]
### Are you requesting a feature, reporting a bug or asking a question?

Question

### What is the current behavior?

Inspired by issue #939 I have been trying to replace the build-in CSS classes of the react survey package. For some reason, I can't manage to actually change the look of most classes. I have tried to copy-paste the CSS classes from the /node_modules/surveyjs-react/survey.css File, tried to find the classes using the selector tool in Firefox, but with no luck. I would love to get some more guidance. I would like to avoid styling the survey using Javascript. 
The only thing I managed to change is the font-family of the survey and disabling the current page number of the survey. 

### What is the expected behavior?

background-color actually changes the color of the selected classes. 

#### Test code

``` css
/* Survey specific */
.sv_main {
    font-family: "Ubuntu", sans-serif;
}

/* Disabling page number */
.sv_main .sv_container .sv_body .sv_progress div.sv_progress_bar > span {
    display: none;
}

.sv_main .sv_container {
    background-color: var(--main-bg-color-dark);
}

.sv_main .sv_p_root > .sv_row:nth-child(2n) {
    background-color: var(--main-bg-color-dark);
}

.sv_main .sv_p_root > .sv_row:nth-child(2n+1) {
    background-color: var(--main-bg-color-dark);
}

.sv_main .sv_body {
    background-color: #4c4c4c;
    border-color: rgb(0, 255, 157);
}

```

```javascript
// styling related imports to the survey component in react
import "survey-react/survey.css";
import "./styles/App.css";
import 'bootstrap/dist/css/bootstrap.min.css';
```

```jsx
// default implementation
<div className={"surveyElement"}>
     <Survey.Survey
         model={model}
         onComplete={this.onCompleteComponent}
         onCurrentPageChanged={this.saveState}
    />
</div>
```

### Specifications

* browser:
* browser version:
* surveyjs platform: react
* surveyjs version: 1.1.15
