### ISSUE TITLE
Allow to set different styles for checkbox items: "Select All" and "None"

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#2307]
Two new item styles were added into checkbox. For standard theme:
```js
    itemSelectAll: "sv_q_checkbox_selectall",
    itemNone: "sv_q_checkbox_none",
```
For modern theme:
```js
    itemSelectAll: "sv-checkbox--selectall",
    itemNone: "sv-checkbox--none",
```
Here is the example for rendering "Select All" in bold text for standard theme.
```css
     .sv_q_checkbox_selectall {
        font-weight: bold;
      }
```
