### ISSUE TITLE
How do I style the page description?

### ISSUE THREAD

**Issue by wrussell96** [surveyjs/survey-library#2308]
How can I style the page description? There is a class tag on the div it's contained in but no classes.

* browser: Chrome
* browser version: Chrome latest
* surveyjs platform react
* surveyjs version: 1.7.17

**Comment by andrewtelnov** [comment]
@wrussell96 We allow to use any class you want for page description. Here is [the example](https://plnkr.co/edit/h19LnMHRh0teq9M2).
Here is the code.
Define the style:
```css
    <style>
        .my-page-description {
            color: red
        }
    </style>
```
Define the custom css for the survey
```js
var myCss = {
    page: {
        description: "my-page-description"
    }
};
```
Merge the current survey CSS with your custom css:
```js
survey.css = myCss;
```

Thank you,
Andrew
