### ISSUE TITLE
Panel title and page title are sharing the same css classes in preview mode

### ISSUE THREAD

**Issue by sh4nks** [surveyjs/survey-library#2498]
### Are you requesting a feature, reporting a bug or asking a question?

Not sure, but it's probably a bug.

### What is the current behavior?

My problem is following:
I have a custom page title style like, for example:
```css
h4.sv_page_title {
    font-weight: 700 !important;
    font-size: 1.75em !important;
    font-style: normal;
    font-stretch: normal;
    line-height: normal;
    letter-spacing: normal;
}
```

This works like a charm in edit mode/display mode.

However when I switch to the preview mode, the page title has the same css class  (``sv_p_title``) as the panel titles.

Preview Mode:
![image](https://user-images.githubusercontent.com/1510708/97541686-d784fa00-19c5-11eb-93c1-743b4ed8d439.png)

Edit/Display Mode (and desired behavior):
![image](https://user-images.githubusercontent.com/1510708/97541722-e9669d00-19c5-11eb-80ab-1bcd79ae8f86.png)

* browser: Chromium 
* browser version: 86.0.4240.111 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.12
