### ISSUE TITLE
Navigation bar items do not fit the smaller screen area

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-library#4826]
Run [this demo](https://surveyjs.io/form-library/examples/s/survey-changenavigation/reactjs) in a separate window, switch to the device with a smaller screen (for example, iPhone XR) and observe the Clear Page button to overlap the survey area:
![image](https://user-images.githubusercontent.com/22372972/189678464-d4b63713-ce41-4a6f-a753-1dfaca09cb08.png)

Source link: [T10605 - Add button beside previous and next in a specific order that adjusts automatically based on mobile resolutions](https://surveyjs.answerdesk.io/internal/ticket/details/T10605).

**Comment by JaneGaid** [comment]
The following CSS resolves the issue:
```css
.sd-body__navigation .sv-action:not(.sv-action--hidden)~.sv-action:not(.sv-action--hidden) {
    margin-left: 0;
}
.sd-root-modern--mobile .sd-body__navigation .sv-action:not(.sv-action--hidden), .sd-root-modern--mobile .sd-body__navigation .sd-btn {
    flex-grow: 0; 
}
.sd-body__navigation .sv-action--hidden {
    display: none; 
}
.sd-body__navigation.sd-action-bar { 
    flex-wrap: wrap; 
    gap: 16px;
}
```
[Example](https://plnkr.co/edit/0ywLDH9K13pfgPQ5).
