### ISSUE TITLE
Matrix Dropdown - Column headers appear regardless of the disabled showHeader option

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5371]
[Example](https://codesandbox.io/s/surveyjs-angular-forked-ignhvo?file=/src/app/components/json.ts).
The `showHeader` option is disabled and a matrix doesn't display column headers:
![image](https://user-images.githubusercontent.com/22372972/208491535-c5a4e50b-c10a-4a43-afff-6eba6a9233a0.png)

On smaller screens, column headers unexpectidely appear:
![image](https://user-images.githubusercontent.com/22372972/208491640-c3b50d41-c677-404a-82a9-b0e1d1a0359d.png)

Original issue: [T11545 - Dimension: any mobile size](https://surveyjs.answerdesk.io/internal/ticket/details/T11545).

**Comment by tsv2013** [comment]
This behavior is implemented via the following CSS rules:
```CSS
@mixin main_m600_styles {
  .sv_main {
    .sv_container {
      .sv_body {
        .sv_p_root {
          .sv_row {
            .sv_q,
            .sv_qstn {
              display: block;
              width: 100% !important;
              .title-left {
                float: none;
              }
              .sv_q_radiogroup_inline,
              .sv_q_checkbox_inline,
              .sv_q_imagepicker_inline {
                display: block;
              }
              table.sv_q_matrix,
              table.sv_q_matrix_dropdown,
              table.sv_q_matrix_dynamic {
                display: block;
                thead {
                  display: none;
                }
                td.sv-table__cell--choice {
                  text-align: initial;
                }
                tbody,
                tr,
                td {
                  display: block;
                }
              }
              table.sv_q_matrix_dropdown,
              table.sv_q_matrix_dynamic {
                td {
                  &:before {
                    content: attr(data-responsive-title);
                  }
                }
              }
              table.sv_q_matrix {
                td {
                  label.sv_q_m_label {
                    display: inline;
                  }
                  &:after {
                    content: attr(data-responsive-title);
                  }
                }
                .sv_q_m_cell {
                  text-align: initial;
                }
              }
            }
          }
        }
      }
    }
  }
}
```
This CSS rule explicitly shows columns on different lines and show labels for them. You can override this behavior via another rule.
