### ISSUE TITLE
font-family is re-declared too often - using css var should be preferred 

### ISSUE THREAD

**Issue by xiel** [surveyjs/survey-library#5490]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
I noticed the build css files contain quite a few font-family declarations, instead of using `var(--font-family)`. In the newer version even more than before. This makes it hard to change the font-family consistently.

for example in https://unpkg.com/survey-core@1.9.68/defaultV2.fontless.css
```css
.sv-popup__button {
  padding: calc(2 * var(--base-unit, 8px)) calc(6 * var(--base-unit, 8px));
  background: var(--background, #fff);
  box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  margin: 2px;
  cursor: pointer;
  font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-style: normal;
  font-weight: 600;
  font-size: calc(2 * var(--base-unit, 8px));
  line-height: calc(3 * var(--base-unit, 8px));
  text-align: center;
  color: var(--primary, #19b394);
  border: none;
  outline: none;
}
```

### What is the expected behavior?
`var(--font-family)` is used consitently as a value, so it can be changed via setting of a css variable in one place (one selector)
