### ISSUE TITLE
Ranking stop working when display flex styles applied 

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-library#5714]
- how to reproduce? just use the following styles for your survey:
```css
.sv-ranking {
  display: flex;
  flex-direction: column;
 }
```

- workaround:
```css
.sd-root-modern .sv-ranking {
  display: flex;
  flex-direction: column;
 }
```

- possible fix (we should test it on mobile devices to apply the fix):
```js
.sv-ranking-shortcut[hidden] {
  display: none;
}
```
