### ISSUE TITLE
Example: Displaying a progress status bar with a percentage inside a survey

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5764]
Original issue: T12299 - How to display a progress status inside survey runner with percentage
https://surveyjs.answerdesk.io/internal/ticket/details/T12299

Displaying a progress status bar with a percentage inside a survey can improve user experience by providing users with a visual indication of their progress. This helps users understand how much of the survey they have completed and how much remains.

**Comment by tsv2013** [comment]
I've created an Angular example - https://codesandbox.io/s/surveyjs-angular-forked-e57x1x?file=/src/app/components/progress.precent.component.ts

Custom component code:
```HTML
<div class="sv-progress-percent">
  <div class="sv-progress-percent__title">
    <span>{{title}}</span>
  </div>
  <div class="sv-progress-percent__indicator">
    <div class="sv-progress-percent__value-bar" [style.width]="value"></div>
  </div>
  <div class="sv-progress-percent__value">
    <span>{{value}}</span>
  </div>
</div>
```
```TS
import {
  Component,
  Input,
  OnChanges,
  OnInit,
  SimpleChanges
} from "@angular/core";
import { AngularComponentFactory } from "survey-angular-ui";
import { SurveyModel } from "survey-core";

import "./progress.precent.component.css";

@Component({
  // tslint:disable-next-line:component-selector
  selector: "sv-ng-progress-buttons",
  templateUrl: "./progress.precent.component.html",
  styleUrls: ["./progress.precent.component.css"]
})
export class ProgressPercentComponent implements OnChanges, OnInit {
  @Input() model!: SurveyModel;
  title: string = "";
  ngOnInit(): void {
    this.title = this.model.progressTitle;
  }
  ngOnChanges(changes: SimpleChanges): void {
    this.title = this.model.progressTitle;
  }
  get value() {
    return this.model.progressValue + "%";
  }
}

AngularComponentFactory.Instance.registerComponent(
  "sv-progress-percent",
  ProgressPercentComponent
);
```
```CSS
.sv-progress-percent {
  display: flex;
  flex-direction: row;
  gap: 16px;
  padding: 16px;
  line-height: 32px;
}

.sv-progress-percent__title {
  font-size: 20px;
  display: flex;
}

.sv-progress-percent__indicator {
  position: relative;
  display: flex;
  width: 100%;
  max-width: 50%;
  height: 32px;
  border: 1px solid green;
}

.sv-progress-percent__value-bar {
  position: absolute;
  background-color: green;
  left: 0;
  top: 0;
  height: 100%;
}

.sv-progress-percent__value {
  font-size: 20px;
  display: flex;
  color: green;
}

.sv_progress-toc {
  min-width: 200px;
}
```
