### ISSUE TITLE
Survey has unnesessary bottom margin

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-library#5878]
This is caused by this code:
```CSS
.sd-container-modern {
    margin-bottom: calc(10 * var(--base-unit, 8px));
}
```

It should work for surveys with the "powered by" footer
