### ISSUE TITLE
Dropdown Matrix Layout is broken when specifying the rowTitleWidth property

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5915]
[Example](https://plnkr.co/edit/YXjfDP0TkodibkM3)
The initial matrix width is 70%. 

If I do not set `rowTitleWidth`, matrix looks as follows:
![image](https://user-images.githubusercontent.com/22372972/229104438-559548e3-3954-4489-b0b2-35be03c83bf0.png)
However, if I set `rowTitleWidth` to `20%` to allow the header take less space, the row header overlaps the first column:
```
const json = {
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "question1",
     "rowTitleWidth": "20%",
     "columns": [
      {
       "name": "Column 1",
       "maxWidth": "25%"
      },
      {
       "name": "Column 2",
       "cellType": "expression",
       "maxWidth": "10%"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ],
     "rows": [
      {
       "value": "Row 1",
       "text": "Row 1"
      },
      {
       "value": "Row 2",
       "text": "Row 2"
      }
     ]
    }
   ]
  }
 ]
}
```
![image](https://user-images.githubusercontent.com/22372972/229104229-f8406cf8-b680-44af-9245-8f065a8b64fd.png)

**Comment by tsv2013** [comment]
```CSS
.responsive-matrix {
  width: 70%;
}
.responsive-matrix .sd-table {
  width: auto;
}
@media (max-width: 600px) {
  .responsive-matrix {
    width: 100%;
  }
  .responsive-matrix .sd-table {
    width: 100%;
  }
}
```
