### ISSUE TITLE
Survey Animation Demo - Rating items' height is changed

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5989]
Run the demo: https://surveyjs.io/form-library/examples/survey-animation/

![image](https://user-images.githubusercontent.com/22372972/231100930-9eaee530-49c9-44bc-a43d-0e354811f825.png)

If you comment the `line-height` attribute of the `expandable` CSS class, this will fix the issue ([Example](https://plnkr.co/edit/Dthel52jvGQw8Cwz))
```css
.expandable {
  background: #fff;
  overflow: hidden;
  color: #000;   
  line-height: 50px;

  transition: all .5s ease-in-out;
  transform-origin: left top;
  transform: scaleY(0);
 }
```
