### ISSUE TITLE
Invalid progress bar layout with default v2 theme within a Bootstrap 5 based project

### ISSUE THREAD

**Issue by dahaupt** [surveyjs/survey-library#8298]
Since a few versions, the progress bar layout is not as expected when using the default v2 theme within a Bootstrap 5 project.

I have also noticed, that several `--sjs` CSS variables are used but not set at all.

Actual layout:
![image](https://github.com/surveyjs/survey-library/assets/15915048/18baa19b-a76e-4d24-8c40-bca048a045db)

Expected layout:
![image](https://github.com/surveyjs/survey-library/assets/15915048/653a7853-d851-4465-b47d-1208f6ce1b54)

Workaround:
```css
.sd-progress-buttons *, 
.sd-progress-buttons ::before, 
.sd-progress-buttons ::after {
    box-sizing: content-box;
}
```

Probably related to the change in #7668.

* browser: Firefox
* browser version: 126.0
* surveyjs platform: jQuery
* surveyjs version: 1.10.4
