### ISSUE TITLE
Multi-Select Matrix - Impossibile to fix a Dropdown column width

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#8382]
https://surveyjs.answerdesk.io/internal/ticket/details/T18505

It is impossible to fix a column width using the `column.width` property. When a dropdown item has a long caption, the column width is expanded. It should be possible to restrict a matrix column width.

**Comment by JaneSjs** [comment]
In the meantime, please apply the following CSS to fix the issue:
```css
.sd-table__cell > .sd-table__question-wrapper .sd-dropdown__value .sv-string-viewer,
.sd-table__cell > .sd-table__question-wrapper .sd-dropdown__value .sd-dropdown__hint-suffix {
       position: absolute;
       left: 0;
       width: 100%;
}
```
