### ISSUE TITLE
How to get the name of a question inside a dynamic panel

### ISSUE THREAD

**Issue by lbonite1** [surveyjs/survey-library#9307]
Hello, I am trying to get the name of the question that I have made changes to. I am doing this

```
submittedForm.onValueChanging.add(async (_, options) => {
    console.log(options);
    // await saveFormData(d30Form);
  });
```
and this is my output

```
name: "actionPanel"
oldValue: Array(1)
   0:
      actionRequired: ['delete']
      campusDeptID: "945"
      employeeName: "Daniel Jaime
      "fromAndToUnits: {fromUnits: 1, toUnits: 0}
      jobTitlePcn: "16159"
      nameOfFormerSupervisor: "101090654"
      numberOfDays: 230
      payGrade: "E25"
      proposedFunding: [{…}][[Prototype]]: Objectlength: 1[[Prototype]]: Array(0)
question: QuestionPanelDynamicModel {dependencies: {…}, propertyHash: {…}, eventList: Array(3), isLoadingFromJsonValue: false, loadingOwner: null, …}
value: Array(1)
   0:
      actionRequired: ['delete']
      campusDeptID: "945"
      employeeName: "Daniel Jaime"
      fromAndToUnits: {fromUnits: 1, toUnits: 0}
      jobTitlePcn: "16159"
      nameOfFormerSupervisor: "101090654"
      numberOfDays: 180
      payGrade: "E25"
      proposedFunding: [{…}]typeOfUnit: ['professsional'][[Prototype]]: Objectlength: 1[[Prototype]]: Array(0)[[Prototype]]: Object

```
I changed the the number of days but instead of giving me the name of the question I changed which is numberOfDays, it gives me the name of the dynamic panel instead. Is there a way for me to get the name of the question I changed inside the dynamic panel instead of giving me the name of the dynamic panel?
